"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "./(componets)/Navbar";
import Footer from "./(componets)/Footer";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

// Load custom local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Load Orbitron from Google Fonts
const orbitron = Orbitron({
  subsets: ["latin"],
});

// //Define metadata for the page
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [isLoginPage, setIsLoginPage] = useState(false);
  const [isRegisterPage, setIsRegisterPage] = useState(false);

  // Track page changes and determine if it's the login page
  useEffect(() => {
    setIsLoginPage(pathname === "/login");
    setIsRegisterPage(pathname == "/register");
  }, [pathname]);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${orbitron.className} antialiased`}
      >
        {/* Conditionally render the Navbar and Footer based on the current route */}
        {!isLoginPage && !isRegisterPage && <Navbar />}
        {children}
        {!isLoginPage && !isRegisterPage && <Footer />}
      </body>
    </html>
  );
}
